# The URL the site will be built for
base_url = "https://sriya-g.github.io"

compile_sass = true
title = "Sriya's Website"
description = ""
generate_feeds = true

taxonomies = [
    {name = "tags", rss = true},
]



